name: 'npm-version-check-action'
description: 'GitHub Action that validates npm package version increments in pull requests to ensure proper semantic versioning'
author: 'Josh Johanning'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  package-path:
    description: 'Path to package.json file (relative to repository root)'
    required: false
    default: 'package.json'
  tag-prefix:
    description: 'Prefix for version tags (e.g., "v" for v1.0.0)'
    required: false
    default: 'v'
  skip-files-check:
    description: 'Always run version check regardless of which files changed. Default (false) only checks if project source files changed, skipping when only tests/docs/configs are modified'
    required: false
    default: 'false'
  include-dev-dependencies:
    description: 'Whether devDependency changes should trigger version bump requirement. Default (false) ignores devDependencies changes and skips package-lock.json analysis when only devDeps change, preventing false positives from dev dependency lock file updates'
    required: false
    default: 'false'
  skip-version-keyword:
    description: 'Keyword in commit messages to skip version check for that commit. Files changed in commits containing this keyword are excluded from the version check. Set to empty string to disable.'
    required: false
    default: '[skip version]'
  token:
    description: 'GitHub token for API access. Required for skip-version-keyword feature to work with shallow clones.'
    required: false
    default: ${{ github.token }}

outputs:
  version-changed:
    description: 'Whether the version was changed'
  current-version:
    description: 'Current version from package.json'
  previous-version:
    description: 'Previous version from latest git tag'

runs:
  using: 'node20'
  main: 'dist/index.js'
