name: 'npm-version-check-action'
description: 'GitHub Action that validates npm package version increments in pull requests to ensure proper semantic versioning'
author: 'Josh Johanning'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  package-path:
    description: 'Path to package.json file (relative to repository root)'
    required: false
    default: 'package.json'
  tag-prefix:
    description: 'Prefix for version tags (e.g., "v" for v1.0.0)'
    required: false
    default: 'v'
  skip-files-check:
    description: 'Skip checking if JS/package files changed (always run version check)'
    required: false
    default: 'false'

outputs:
  version-changed:
    description: 'Whether the version was changed'
  current-version:
    description: 'Current version from package.json'
  previous-version:
    description: 'Previous version from latest git tag'

runs:
  using: 'node20'
  main: 'dist/index.js'
