env:
  node: true
  es2021: true
  jest: true

extends:
  - eslint:recommended
  - plugin:github/recommended
  - plugin:jest/recommended
  - plugin:prettier/recommended

ignorePatterns:
  - 'node_modules/'
  - 'dist/'
  - 'coverage/'
  - '.nyc_output/'
  - '*.min.js'

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  i18n-text/no-en: 'off'
  camelcase: 'off' # GitHub API uses snake_case properties
  object-shorthand: 'off' # Allow explicit property syntax for clarity
  import/no-commonjs: 'error' # Using ES modules, not CommonJS
  import/no-namespace: 'off' # Allow * namespace imports for ES modules
  import/no-unresolved: 'off' # False positives for packages in node_modules; Node.js resolves imports correctly
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_'
  no-console: warn
  prefer-const: error
  no-var: error
