env:
  node: true
  es2021: true
  jest: true

extends:
  - eslint:recommended
  - plugin:github/recommended
  - plugin:jest/recommended
  - plugin:prettier/recommended

ignorePatterns:
  - 'node_modules/'
  - 'dist/'
  - 'coverage/'
  - '.nyc_output/'
  - '*.min.js'

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  i18n-text/no-en: 'off'
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_'
  no-console: warn
  prefer-const: error
  no-var: error
