name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Required for git tag comparison

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run formatting check
        run: npm run format:check

      - name: Run tests
        run: npm test

      - name: Package the action
        run: npm run package

      - name: Test the action
        uses: ./
        with:
          package-path: 'package.json'
          tag-prefix: 'v'

      - name: Validate action.yml
        run: |
          # Basic validation that action.yml is valid YAML
          if command -v yq &> /dev/null; then
            yq eval '.' action.yml > /dev/null
          else
            # Fallback to python yaml check
            python -c "import yaml; yaml.safe_load(open('action.yml'))"
          fi
